version: 2

defaults: &defaults
    working_directory: ~/boltz-middleware

    docker:
      - image: circleci/node:lts

jobs:
  dependencies:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-v3

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}-v3
          paths:
            - ./node_modules

      - persist_to_workspace:
          root: ~/
          paths: boltz-middleware

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: Install rsync
          command: 'sudo apt-get update -y && sudo apt-get -y install rsync'

      - run:
          name: Compile
          command: npm run compile

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: Lint
          command: npm run lint

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: Test
          command: npm run test

workflows:
  version: 2

  build-and-test:
    jobs:
      - dependencies

      - build:
          requires:
            - dependencies

      - lint:
          requires:
            - dependencies

      - test:
          requires:
            - dependencies
