version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:lts
    steps:
      - checkout:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: update
          command: 'sudo apt-get update -y && sudo apt-get -y install rsync'
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@lts'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: compile
          command: npm run compile
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm run test
